### ISSUE TITLE
Which entity types are supported?

### ISSUE THREAD

**Issue by adorobis** [dannerph/esphome_vitoconnect#2]
Hello, 
Which entity types are supported by your custom component? Is it read-only ones or also you enable controlling them (e.g. number, select etc to control temperatures and operating modes)?

Many thanks for your work!

**Comment by dannerph** [comment]
Currently only 2 Byte and 4 Byte values are supported in ready only Mode. That ist enough for my use case.
For more advanced Features, follows this PR: https://github.com/esphome/esphome/pull/4453
