### ISSUE TITLE
Set parameter

### ISSUE THREAD

**Issue by MomoRC-tech** [dannerph/esphome_vitoconnect#3]
Is there a way to set a parameter as well?

________________________________________________________
Currently I am using VitoWIFI compiled with Arduino to read and write to my Viessmann Heatpump.

**Comment by dannerph** [comment]
Hi @Momo-GitHub-1 
Setting parameter is not supported and I do not have plans to extend it currently.
If you want use esphome to set values as well, check this PR https://github.com/esphome/esphome/pull/4453
