### ISSUE TITLE
KW Protocol

### ISSUE THREAD

**Issue by Wurzelfuchs** [dannerph/esphome_vitoconnect#4]
Hi. 
Is it possible to integrate the KW protocol?

**Comment by Wurzelfuchs** [comment]
Eine mögliche Anlage zum Test steht in 94099 😉

**Comment by dannerph** [comment]
Hi @Wurzelfuchs,
the open-source idea works, someone else extended my code with KW protocol. I fetched those code snippets, but I am not able to test it. Please report back if it is not working.
